[default]
extend-ignore-re = [
    "(?Rm)^.*(#|//)\\s*spell-checker:disable-line.*$",
]

[files]
extend-exclude = [
    "*.log",
    "tests/data",
    "project_context.md",
]

[default.extend-words]
PN = "PN"
numer = "numer"
flate = "flate"
ded = "ded"
